# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 02:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.SmallIntegerField(choices=[(1, 'boy'), (2, 'girl')], default=1)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('sign', models.CharField(blank=True, max_length=128, null=True)),
                ('acount', models.IntegerField(blank=True, default=0, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='Image/')),
                ('book', models.CharField(blank=True, max_length=128, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
