# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 11:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_auto_20170811_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chapter_id', models.IntegerField(primary_key=True, serialize=False)),
                ('chapter_title', models.CharField(max_length=128, verbose_name='标题')),
                ('chapter_content', models.TextField(verbose_name='章节内容')),
                ('create_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.TimeField(auto_now=True)),
                ('comment_content', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('novel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.SmallIntegerField(choices=[(1, '玄幻'), (2, '武侠'), (3, '仙侠')], default=1)),
                ('novel_name', models.CharField(max_length=128)),
                ('writer', models.CharField(max_length=128)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('wordcount', models.IntegerField()),
                ('updatatime', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Novel'),
        ),
    ]
